### ISSUE TITLE
'Tile' could not be found

### ISSUE THREAD

**Issue by gitunit** [jmerzian/UnityProceduralIsland#1]
unity3d is complaining that the 'Tile' class or nampespace could not be found:

Assets/UnityProceduralIsland-master/VoxelTerrain.cs(16,31): error CS0246: The type or namespace name `Tile' could not be found. Are you missing a using directive or an assembly reference?

also you in your README you write about attaching "VoxelTerrain.cpp", did you mean "VoxelTerrain.cs" ? i guess a typo happened there ;)

**Comment by jmerzian** [comment]
Comment it out, I was attempting to pull a small portion out of a significantly larger project... and yes... I might have have accidentally swapped languages there...
